services:
  mongo:
    image: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:${MONGO_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD:${MONGO_PASSWORD}"
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
    ports:
      - 27017:27017

volumes:
  mongo-db:
  mongo-config:
